version: "3.9"
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    command: bash -c "npm run dev"
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"

networks:
  postgres-network:
    driver: bridge
